import type { GameConfig } from '../types';

/**
 * Game template - copy this folder to create a new game.
 * Scenes: Boot → Preload → Home → Gameplay → GameOver
 */
export const gameTemplateConfig: GameConfig = {
  id: 'game-template',
  name: 'New Game',
  version: '0.1.0',
  scenes: ['Boot', 'Preload', 'Home', 'Gameplay', 'GameOver'],
  width: 720,
  height: 1280,
};

// Template scenes are generated by `npm run create-game`
// See scripts/create-game.ts
